name: Test

on: 
  workflow_call:
    inputs:
      logLevel:
        type: string
        default: 'warning'

        # type: choice
        # default: 'warning'
        # options:
        #   - info
        #   - warning
        #   - debug

jobs:
  task:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
