name: Test

on: 
  workflow_call:
    inputs:
      logLevel:
        type: choice
        default: 'warning'
        options:
          - info
          - warning
          - debug

        # type: string
        # default: 'warning'


jobs:
  task:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
